@startuml
mix_actor 申込ユーザ


'left to right direction

'hide circle
'hide method


package 入退会サービス {

    class 入会プロセス{
        入会するユーザ情報

        入会手続きを実行する(入会するユーザ情報)
    }

    class 退会プロセス{
        退会するユーザ情報

        退会手続きを実行する(退会するユーザ情報)
    }

    class 入会するユーザ情報{
        氏名
        氏名かな
        性別
        生年月日
        郵便番号
        住所
        電話番号
        昼間連絡先
        希望するメールアドレス
        コース情報
        クレジットカード番号
        クレジットカード有効期限
        クレジットカードセキュリティコード

        クレジットカード審査情報を生成する()
        入会審査情報を生成する()
    }

    class 退会するユーザ情報{
        会員ID
    }

    入会プロセス --> 入会するユーザ情報
    退会プロセス --> 退会するユーザ情報

}
package ユーザ番号{

    class ユーザID{
        発行されたユーザID
    }

}

package 会員情報{

    class 会員情報{
        ユーザID
        メールアドレス
        会員ID
        会員パスワード
        コース情報
        会員状態
    }

    enum コース情報{
        ベーシック
        ニコニコ
    }


    interface 会員情報Repository{
        会員を登録する()
        ユーザIDを検索する(会員ID)
        ユーザIDを検索する(入会審査情報)
        会員情報を更新する()
    }

    enum 会員状態{
        入会申請中
        入会中
        退会申請中
        退会中
    }

    会員情報Repository --> 会員情報
    会員情報 --> 会員状態
    会員情報 --> コース情報
    会員情報 --> ユーザID


}
入会プロセス ---> 会員情報Repository
'入会プロセス -> ユーザID発番Repository

package ユーザ情報パッケージ {

    class ユーザ情報{
        ユーザID
        氏名
        氏名かな
        生年月日
        性別
        郵便番号
        住所
        電話番号
        昼間連絡先

        大人ですか()
    }


    interface ユーザ情報Repository{
        ユーザを登録する()
        ユーザを検索する()
    }

    class 入会審査情報{
        氏名
        氏名かな
        生年月日
    }

    ユーザ情報Repository --> 入会審査情報
    ユーザ情報Repository --> ユーザ情報
    ユーザ情報 --> ユーザID
    入会プロセス ---> ユーザ情報Repository
}


package クレジットカード {


    class クレジットカード情報{
        ユーザID
        カード番号
        カード有効期限
        カードセキュリティコード

        有効期限は過ぎていないか()
    }

    interface クレジットカードRepository{
        クレジットカードを登録する()
        クレジットカードを検索する()

    }

    class クレジットカード審査情報{
        カード番号
        カード有効期限
        カードセキュリティコード
    }

    クレジットカードRepository --> クレジットカード情報
    クレジットカードRepository --> クレジットカード審査情報
    クレジットカード情報 --> ユーザID
    入会プロセス ---> クレジットカードRepository
}

class 登録情報{
    クレジットカード
    個人情報
    希望するメールアドレス
}



入会するユーザ情報 -> 入会審査情報
入会するユーザ情報 -> クレジットカード審査情報
 申込ユーザ -r-> 登録情報
 申込ユーザ --> 入会プロセス
 申込ユーザ --> 退会プロセス





' クレジットカード -> クレジットカード審査情報

@enduml
